# <font color='navygray'>MF013 Análisis de inversión:  Introducción a Algotrading</font>
Por Carlos Crespo Elizondo, MSF<br>
Clase del 21-10-20

Mi libreta de la clase acompañada con comentarios de lo que fuimos haciendo!

## <font color='navygray'>1. Sobre la clase pasada (14-10-20)</font>
La clase pasada vimos:
1. Los diccionarios
    * Que son y sus elementos (llaves/valores)
    * Crear un diccionario
    * Accesar a sus valores
    * Modificar sus valores
    * Alta de llaves nuevas
1. For Loop
1. La función "f" para concatenar los valores de variables
1. La función "Range", para crear rangos numéricos
1. For Loops usados en diccionarios
    * Accesar solo a las llaves del diccionario
    * Accesar solo a los valores del diccionario
    * Accesar a la llave y al valor correspondiente
    
Quedaron pendientes dos temas:
1. While Loop
1. IF's

## <font color='navygray'>2. Imagina la siguiente situación:</font>
Tenemos un portafolio con cinco activos financieros.  El costo de cada uno de los activos lo capturamos en la lista "*__lista_precios_activos__*".  El costo de las comisiones (10%) por la compra de cada activo lo capturamos en la lista "*__lista_costos_comisiones__*".

In [1]:
lista_precios = [12, 5, 20, 18, 10]
lista_comision = [1.2, .5, 2, 1.8, 1]

Ahora queremos calcular el costo unitario final de cada activo.  De alguna manera pudieramos creer que simplemente sumamos las dos listas.  Al sumar las dos listas, realmente las estamos juntando.

In [2]:
lista_precio_final = lista_precios + lista_comision
lista_precio_final

[12, 5, 20, 18, 10, 1.2, 0.5, 2, 1.8, 1]

Si queremos sumar los elementos de una lista con los elementos de otra lista en base a su posición en el index usando unicamente PYTHON, es decir, sin el apoyo de otras librerías, tenemos que hacer lo siguiente:

In [3]:
lista = []

for activo, comision in zip(lista_precios, lista_comision):
    lista.append(activo + comision)

Este ejemplo lo uso de pretexto para darle paso a la introducción a Numpy!

## <font color='navy'>3. Numpy</font>
![alt text](https://drive.google.com/uc?export=view&id=179rEqet8kzNlBEx0YVJTY1m04YL_2wz_)

La página web de NumPy, lo define como:
> *Numpy es __el__ paquete fundamental para la computación científica en Python.  Contiene entre otras cosas:*
* _Un poderoso arreglo multidimensional_
* _Herramientas para integrar código de C/C++, Fortran_
* _Algebra lineal, transformaciones de Fourier, capacidad de generación de números aleatorios._<br><br>

>_A parte de su uso científico obvio, Numpy puede ser usado de manera eficiente como un contenedor multidimensional de datos, lo que le permite a Numpy integrarse se manera natural con una gran variedad de bases de datos._

Las librerías las cargamos al sistema utilizando la función *__import__*, seguido del nombre de la librería a importar.  También python nos da la oportunidad de ponerle un sobrenombre a la librería.<br><br>
Por convención el sobrenombre que utilizamos para importar Numpy es "np":

In [4]:
import numpy as np

El ejemplo anterior que nos llevó 5 líneas de código, lo podemos hacer en tres líneas y con una interpretación más fácil y limpia:

In [5]:
array_precios = np.array([12, 5, 20, 18, 10])
array_comisiones = array_precios * 0.1
array_precio_final = array_precios + array_comisiones

In [6]:
array_precio_final

array([13.2,  5.5, 22. , 19.8, 11. ])

Recuerden que numpy entregó un array (arreglo en español), que es la forma de transformar una lista a una especie de "vector".

Esto no lo vimos en clase pero si el objetivo es tener el precio final, podemos hacer el código en dos líneas:

In [7]:
array_precios = np.array([12, 5, 20, 18, 10])
array_precio_final = array_precios*1.1

In [8]:
array_precio_final

array([13.2,  5.5, 22. , 19.8, 11. ])

Otra variante que vimos en la clase es definir con una variable la comisión y después utilizar la variable para calcular los valores:

In [9]:
comision = .1
array_precios = np.array([12, 5, 20, 18, 10])
array_comisiones = array_precios * comision

In [10]:
array_comisiones

array([1.2, 0.5, 2. , 1.8, 1. ])

In [11]:
array_precio_final = array_precios + array_comisiones

In [12]:
array_precio_final

array([13.2,  5.5, 22. , 19.8, 11. ])

Recuerden que Numpy tiene muhcas funciones al igual que valores, como son $\pi$ y $e$

In [13]:
np.pi

3.141592653589793

In [14]:
np.e

2.718281828459045

Podemos crear rangos númericos en Numpy con la función "*__arange( )__*

In [15]:
x = np.arange(11)

In [16]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Esto tampoco lo vimos en clases, pero recuerden que comentamos que podemos definir un inicio, un final y los pasos, igual que al utilizar la función "*__range__* de Python:
$$arange(empieza, termina, pasos de incremento)$$

In [17]:
y = np.arange(10, 101, 10)
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [18]:
z = np.arange(10,-1,-1)
z

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## <font color='navy'>4. Pandas</font>
![alt text](https://drive.google.com/uc?export=view&id=178XxLPUuqJ-us_q67ViEoWMlrsc_8X1o)

>"*__pandas__ es una librería de código abierto que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento y fáciles de usar para el lenguaje de programación Python.*"<cite data-cite='pandas'>(pydata.org, 2019)</cite><br><br>

Pandas tiene varios tipos de estructuras de datos.  Los dos más importantes son:
* __*Series*__: _Arreglo unidimensional de datos y contiene etiquetas para los datos._
* __*DataFrames*__:  _Es una estructuras de datos que contiene ejes etiquetados (filas y columnas).  Es la estructura de datos principal en pandas_

La convención para importar pandas es utilizar "__*pd*__".

In [19]:
import pandas as pd

Vamos a crear una Serie de pandas utilizando la función *__"Series"__*:

In [20]:
serie_precios = pd.Series([13.2,  5.5, 22. , 19.8, 11.])
serie_precios

0    13.2
1     5.5
2    22.0
3    19.8
4    11.0
dtype: float64

En el resultado anterior, podemos ver que cada valor está directamente asociado a un index-etiqueta.  En este caso como no definimos los nombres de los index, pandas los definió de manera numérica.<br><br>
Recuerda que en este caso debemos de indicarle a Python que la función "*__Series__*" es parte de Pandas, por eso utilizamos la conotación "*__pd.Series__*".<br><br>
Los valores de la Serie los podemos accesar por su *__index__*:

In [21]:
serie_precios[0]*serie_precios[3]

261.36

Por rangos:

In [22]:
serie_precios[:3]

0    13.2
1     5.5
2    22.0
dtype: float64

In [23]:
serie_precios[3:]

3    19.8
4    11.0
dtype: float64

Las Series también pueden contener texto:

In [24]:
serie_texto = pd.Series(['a', 'a', 'b'])
serie_texto

0    a
1    a
2    b
dtype: object

Ahora vamos a construir una Serie utilizando fechas como index.  Primero definiremos una lista con las fechas y después haremos la Serie:

In [25]:
lista_fechas = ['10/10/20', '10/11/20', '10/12/20', '10/13/20', '10/14/20']

In [26]:
serie_precios = pd.Series([13.2,  5.5, 22. , 19.8, 11.], index = lista_fechas)
serie_precios

10/10/20    13.2
10/11/20     5.5
10/12/20    22.0
10/13/20    19.8
10/14/20    11.0
dtype: float64

Ahora podemos accesar a los valores utilizando las fechas o el valor del index:

In [27]:
serie_precios['10/13/20']

19.8

In [28]:
serie_precios[3]

19.8

In [29]:
serie_precios[-2]

19.8

También podemos seleccionar más de una fecha de la siguiente manera

In [30]:
serie_precios[['10/12/20', '10/13/20']]

10/12/20    22.0
10/13/20    19.8
dtype: float64

Esta forma causó algo de confusión por los corchetes dobles.  Veanlo de la siguiente manera, el primer corchete representa la selección de un index, como lo habíamos hecho desde Python, el segundo corchete representa una lista, es este caso los una lista con las fechas de interés.<br><br>
Una alternativa para aclarar esta confusión es primero crear una lista y después seleccionar las fechas:

In [31]:
lista_rangos = ['10/12/20', '10/13/20']
serie_precios[lista_rangos]

10/12/20    22.0
10/13/20    19.8
dtype: float64

Podemos filtrar valores que cumplen cierta condición, como ver todos aquellos que sean mayores a 15:

In [32]:
serie_precios[serie_precios>15]

10/12/20    22.0
10/13/20    19.8
dtype: float64

Podemos interpretar la lógica en dos partes:
1. Entre corchetes:  En "*__serie_precios__*" selecciona todos los valores mayores de 15 
1. Continuación:  Que se encuentran en "*__serie_precios__*"

Quizá ahorta no tenga sentido esta lógica, por lo pronto veanló como una receta de cocina.  Más adelante hará sentido!<br><br>
Tabla con las operaciones lógicas de Python
<table>
  <tr>
    <th style="text-align:center;">Simbolo</th>
    <th style="text-align:center;">Descripción</th>
  </tr>
  
  <tr>
    <td style="text-align:center;">==</td>
    <td style="text-align:right;">Igualdad</tr>
  
  <tr>
    <td style="text-align:center;">!=</td>
    <td style="text-align:right;">Desigualdad</td>
  </tr>
  
  <tr>
    <td style="text-align:center;">&gt;</td>
    <td style="text-align:right;">Mayor que</td>
  </tr>

  <tr>
    <td style="text-align:center;">&gt;=</td>
    <td style="text-align:right;">Mayor igual que</td>
  </tr>
  
  <tr>
    <td style="text-align:center;">&lt;</td>
    <td style="text-align:right;">Menor que</td>
    </tr>

  <tr>
    <td style="text-align:center;">&lt;=</td>
    <td style="text-align:right;">Menor igual que</td>
    </tr>
 
</table>

Las siguientes celdas se explican solas:

In [33]:
serie_precios[serie_precios==19.8]

10/13/20    19.8
dtype: float64

In [34]:
serie_precios * 100

10/10/20    1320.0
10/11/20     550.0
10/12/20    2200.0
10/13/20    1980.0
10/14/20    1100.0
dtype: float64

In [35]:
serie_precios - serie_precios

10/10/20    0.0
10/11/20    0.0
10/12/20    0.0
10/13/20    0.0
10/14/20    0.0
dtype: float64

In [36]:
serie_precios[2]

22.0

Podemos construir una Serie a partir de un diccionario.  La llave del diccionario se toma como el index:

In [37]:
dicc_cierre = {'CX':6, 'ALFAA':20, 'FEMSAUBD':135, 'AMXL':23}
dicc_cierre

{'CX': 6, 'ALFAA': 20, 'FEMSAUBD': 135, 'AMXL': 23}

In [38]:
precios_cierre = pd.Series(dicc_cierre)
precios_cierre

CX            6
ALFAA        20
FEMSAUBD    135
AMXL         23
dtype: int64

In [39]:
precios_cierre['CX']

6

Para ordenar los valores de mayor a menor, utilizamos *__.sort_values( )__* y utilzando el argumento (opción) "*__ascending__*" igual a falso

In [40]:
precios_cierre.sort_values(ascending=False)

FEMSAUBD    135
AMXL         23
ALFAA        20
CX            6
dtype: int64

In [41]:
precios_cierre

CX            6
ALFAA        20
FEMSAUBD    135
AMXL         23
dtype: int64

Los cambios anteriores no fueron permanentes.  Para hacerlos permanentes utilizamos el argumento (opción) "*__inplace = True__*". Este argumento lo veremos en muchas funciones de pandas!

In [42]:
precios_cierre.sort_values(ascending=False, inplace = True)

In [43]:
precios_cierre

FEMSAUBD    135
AMXL         23
ALFAA        20
CX            6
dtype: int64

Ahora vamos a crear un DATAFRAME a partir de un diccionario doble.  Para no perder tiempo, les pasé los valores del diccionario através de un mensaje en TEAMS, pero a varios de ustedes les registro errores.  Para la siguiente clase tendré habilitado una mejor manera de compartir mis códigos en vivo, sin la necesidad de estar haciendo copy-paste en TEAMS y que ustedes lo puedan accesar en cualquier instante

In [44]:
ingresos_anuales = {'Cemex':{"'15":249.4, "'16":251.2, "'17":257.4, "'18":276.8, "'19": 287}, 
                    'Alfa':{"'15":258.3, "'16":293.7, "'17":317.6, "'18":366.4, "'19":370.4},
                    'Femsa':{"'15":311.5, "'16":399.5, "'17":460.4, "'18":399.5, "'19":498.3}}

La notación de las fechas creo que no fué la más óptima al utilizar las comillas sencillas junto a las comillas dobles!!!  :(

Mejor voy a eliminar las comillas utilizando FIND AND REPLACE en el menú EDIT de Juputer/Colab.  En la opción find puse *__"'__* y en la opción replace with *__"20__*, puesto que se vería muy solo el 15!

In [2]:
ingresos_anuales = {'Cemex':{"2015":249.4, "2016":251.2, "2017":257.4, "2018":276.8, "2019": 287}, 
                    'Alfa':{"2015":258.3, "2016":293.7, "2017":317.6, "2018":366.4, "2019":370.4},
                    'Femsa':{"2015":311.5, "2016":399.5, "2017":460.4, "2018":399.5, "2019":498.3}}

Este es un diccionario con diccionarios internos.  Para accesar a un valor seleccionas las llaves de interés separadas por corchetes

In [4]:
ingresos_anuales['Cemex']['2019']

287

Con el diccionario anterior podemos construir un DataFrame en donde las llaves primarias toman las columnas y las secundarias los renglones

In [47]:
df = pd.DataFrame(ingresos_anuales)
df

Cemex   Alfa  Femsa
2015  249.4  258.3  311.5
2016  251.2  293.7  399.5
2017  257.4  317.6  460.4
2018  276.8  366.4  399.5
2019  287.0  370.4  498.3

Podemos accesar a los valores de Alfa de la siguiente manera:

In [48]:
df['Alfa']

2015    258.3
2016    293.7
2017    317.6
2018    366.4
2019    370.4
Name: Alfa, dtype: float64

Para seleccionar por index, utilizamos *__.loc__*

In [49]:
df.loc["2017"]

Cemex    257.4
Alfa     317.6
Femsa    460.4
Name: 2017, dtype: float64

O *__.iloc__* para seleccionar por el lugar del index

In [50]:
df.iloc[2]

Cemex    257.4
Alfa     317.6
Femsa    460.4
Name: 2017, dtype: float64

Las operaciones se aplican a todos los elementos del DataFrame:

In [51]:
df_usd = df/20.5
df_usd

Cemex       Alfa      Femsa
2015  12.165854  12.600000  15.195122
2016  12.253659  14.326829  19.487805
2017  12.556098  15.492683  22.458537
2018  13.502439  17.873171  19.487805
2019  14.000000  18.068293  24.307317

In [ ]:
df_excel = pd.read_excel()

<font color='red'>Te acuerdas cual fue nuestra primera línea de código en Python?</font>

In [52]:
print('Hola!')

Hola!


<font color='red'>Hemos avanzado muchísimo y los FELICITO a cada uno de ustedes por su dedicación y disposición a aprender cosas nuevas que a lo mejor no tenían contemplado aprender!!!  Con estas bases sólidas ya estamos LISTOS para meternos de lleno al trading algoritmico y pisar el acelerador.</font>

<font color='navy'>La manera que hemos venido aprendiendo Python es presentar una función y luego explicar como funciona.  A partir de este momento vamos a hacer las cosas a la inversa!  En base a lo que necesitamos vamos a buscarle una solución!</font>